server:
  port: 9000

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://15.164.216.197:3306/taco?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver




