server:
  port: 9000

spring:
  datasource:
    username: root
    password: bb2848
    url: jdbc:mysql://localhost:3306/taco?characterEncoding=UTF-8&serverTimezone=UTC&&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver





