server:
  port: 5050

spring:
  datasource:
    username: root
    password: bb2848
    url: jdbc:mysql://localhost:3306/taco?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver





